### PR TITLE
Blank avatar (read for more info)

### PR DESCRIPTION
**Pull request by JKJKLOLOLOL**
Front 
- displays annonymous avatar and attachs it to user if user have no avatar

Explore (User index)
-  the page can now run even if the user does not has a record. (proficiency, height, weight ,etc.)
- Changed header text
- added bottom margin for navbar
- displaying avatars as bg image
- card and images edges made rounder
- name as text overlay over image
- discipline/proficiency, height and weight up and in bubbles

User profile (show)
-  the page can now run even if the user does not has a record. (proficiency, height, weight ,etc.)
- added back button (to explore)
- added bottom margin for navbar
- either Edit profile or Request button will show
- put height and weight in bubbles
- realigned name age and gender
-moved styles to SCSS

Chatroom
- added bottom margin for navbar
- chat can now be scrollable while text field still visible even which tons of messages
-added styles to html file (needs to be refactored, delete prev scss file)

### CODE REVIEW

**Review by ShiJieCodes — COMMENTED** [review]
Looks good! for those parts i understand

**Review by ShiJieCodes — COMMENTED** [review]
wa zai!

**Review by ShiJieCodes — COMMENTED** [review]
awesome

**Review by IreneHernandezO — APPROVED** [review]
Looks very good!

**Review by TimeToGitGoing — APPROVED** [review]
beautiful work

**Pull request merged**
