### PR TITLE
Friends page and more

### PR DESCRIPTION
**Pull request by JKJKLOLOLOL**
**Preference model + Preference edit**
-adjusted validation
-standardised disciplines (martial arts with belt ranking)
- standarised gender options

**Explore** 
Problem: run into error when using new user with no preferences
- Creates new preference for current_user is preference not present
- Added to and refacotred User controller (can now view 'ALL' genders)
- added face zoom on images

**Friends**
- Split code into acceptor(accept or reject) and requestor (Pending review)
- friend method on pages user controller
- linked avatar to user profile
- added last name

### CODE REVIEW

**Review by ShiJieCodes — COMMENTED** [review]
Looks good

**Review by IreneHernandezO — APPROVED** [review]
Amazing job!

**Review by TimeToGitGoing — APPROVED** [review]
nicely done

**Review by TimeToGitGoing — APPROVED** [review]
AMAZING!!!

**Pull request merged**
